services:
  databasescon:
    build: ./database/
    image: database
    ports:
      - "3306:3306"
    volumes:
      - ./database:/docker-entrypoint-inidb.d/
    container_name: databasescon
    environment:
      - MYSQL_ROOT_PASSWORD=trimitr56
      - TZ=Asia/Bangkok
    restart: on-failure
  backendcon:
    build: ./backend/
    image: backend
    ports:
      - "8080:8080"
    links:
      - databasescon
    restart: on-failure
    environment:
      - MYSQL_PATH=databasescon
      - MYSQL_PORT=3306
      - MYSQL_DATABASE=oasip
      - TZ=Asia/Bangkok
    container_name: backendcon
  frontendcon:
    image: frontend
    build: ./frontend
    restart: unless-stopped
    volumes:
      - ./frontend/:/var/local/app:cached
      #- ./frontend/config/nginx/proxy.conf:/etc/nginx/conf.d/proxy.conf:cached
      - ./frontend/config/nginx/default.conf:/etc/nginx/conf.d/default.conf:cached
    container_name: frontendcon
    ports:
      - "3000:80"
  proxy_nginx_frontend:
    image: nginx:1.19.1
    restart: unless-stopped
    volumes:
      #- ./front-end/config/nginx/default.conf:/etc/nginx/conf.d/default.conf:cached
      - ./frontend/config/nginx/Proxy.conf:/etc/nginx/conf.d/Proxy.conf:cached
      - ./frontend/logs/nginx:/var/log/nginx:cached
    container_name: proxy_nginx_frontend
    ports:
      - "80:80"
    depends_on:
      - frontendcon
